version: '2.0'

services:
  master:
    image: dockerjk
    environment:
      JAVA_OPTS: "-Djava.awt.headless=true"
    ports:
      - "50000:50000"
      - "8084:8080"
    volumes:
      - /var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    container_name: dockerjk
    tty: true
    #depends_on:
     # kafka:
    #    condition: service_healthy
    #links:
    #    - kafka
    #entrypoint: bash -lc "chmod 600 /var/run/docker.sock"

  #kafka:
  ##  image: landoop/fast-data-dev
   # container_name: dkafka
   # ports:
   #   - "2181:2181"
   #   - "3030:3030"
   #   - "8081:8081"
   #   - "8082:8082"
   #   - "8083:8083"
   #   - "9092:9092"
   # environment:
   #   - ADV_HOST=kafka
   # healthcheck:
   #     test: ["CMD", "curl", "-f", "http://localhost:3030"]
   #     interval: 30s
   #     timeout: 10s
   #     retries: 5